version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.9
    - 17.4.1
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.9
    - 4.2.3
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: all-contributors-cli
    versions:
    - 6.19.0
